/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.renta.view;

/**
 *
 * @author PRINCIPAL-PC
 */
public class AdminPageFirst extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminPageFirst
     */
    public AdminPageFirst() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabView = new javax.swing.JTabbedPane();
        jtabAdd = new javax.swing.JTabbedPane();
        jtabView = new javax.swing.JTabbedPane();
        jtabSearch = new javax.swing.JTabbedPane();
        jtabDelete = new javax.swing.JTabbedPane();

        tabView.addTab("Agregar Vehiculos a rentar", jtabAdd);
        tabView.addTab("Visualizar Vehiculos", jtabView);
        tabView.addTab("Buscar (id)", jtabSearch);
        tabView.addTab("Eliminar Vehiculos a rentar", jtabDelete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabView, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabView, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtabAdd;
    private javax.swing.JTabbedPane jtabDelete;
    private javax.swing.JTabbedPane jtabSearch;
    private javax.swing.JTabbedPane jtabView;
    private javax.swing.JTabbedPane tabView;
    // End of variables declaration//GEN-END:variables
}
