/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.renta.view;

import com.renta.controller.AdminController;
import javax.swing.JOptionPane;

/**
 *
 * @author PRINCIPAL-PC
 */
public class LoginAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdministrador
     */
    public LoginAdministrador() {
        initComponents();
        setLocationRelativeTo(null);//para que la imagen quede centrada
       // setResizable(false); //para que la ventana no se maximice
        setTitle("Main"); //colocar nombre de la ventana        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUsuarioAdmin = new java.awt.TextField();
        passAdmin = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtUsuarioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAdminActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuarioAdmin);
        txtUsuarioAdmin.setBounds(250, 160, 120, 20);

        passAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passAdminActionPerformed(evt);
            }
        });
        getContentPane().add(passAdmin);
        passAdmin.setBounds(251, 200, 120, 20);

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(120, 250, 73, 23);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(270, 250, 53, 23);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenFondo/fondoAdministrador.png"))); // NOI18N
        lblFondo.setText("jLabel2");
        getContentPane().add(lblFondo);
        lblFondo.setBounds(-20, 0, 510, 374);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        boolean valid = false;
        AdminController controller = new AdminController();
        valid = controller.loginAdministrador(txtUsuarioAdmin.getText(),
                passAdmin.getText());
        if (valid) {
            AdminPageFirst adminFirst = new AdminPageFirst();
        }else{
            JOptionPane.showConfirmDialog(this, "Usuario o Contraseña "
                    + "Incorrectos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtUsuarioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAdminActionPerformed

    private void passAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JPasswordField passAdmin;
    private java.awt.TextField txtUsuarioAdmin;
    // End of variables declaration//GEN-END:variables
}
